# Generated by Django 3.2.6 on 2022-12-04 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ad_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
