# Generated by Django 3.2.6 on 2022-12-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_rename_created_ad_ad_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
